
column_names <- c(
  'GPS_Time', 'Device_Time', 'Longitude', 'Latitude',
  'GPS_Speed_(Meters/second)', 'Horizontal_Dilution_of_Precision',
  'Altitude', 'Bearing', 'G(x)', 'G(y)', 'G(z)', 'G(calibrated)',
  '0-100kph_Time(s)', 'Absolute_Throttle_Position_B(%)',
  'Acceleration_Sensor(Total)(g)', 'Acceleration_Sensor(X_axis)(g)',
  'Acceleration_Sensor(Y_axis)(g)', 'Acceleration_Sensor(Z_axis)(g)',
  'Accelerator_PedalPosition_D(%)', 'Accelerator_PedalPosition_E(%)',
  'Accelerator_PedalPosition_F(%)', 'Actual_engine_%_torque(%)',
  'Air_Fuel_Ratio(Commanded)(:1)', 'Ambient_air_temp(°C)',
  'Average_trip_speed(whilst_moving_only)(km/h)',
  'Average_trip_speed(whilst_stopped_or_moving)(km/h)',
  'Barometric_pressure_(from_vehicle)(psi)',
  'CO₂_in_g/km_(Average)(g/km)', 'DPF_Pressure(psi)',
  'DPF_Temperature(°C)', 'Engine_Coolant_Temperature(°C)',
  'Engine_kW_(At_the_wheels)(kW)', 'Engine_Load(%)',
  'Engine_Load(Absolute)(%)', 'Engine_Oil_Temperature(°C)',
  'Engine_reference_torque(Nm)', 'Engine_RPM(rpm)',
  'Fuel_cost_(trip)(cost)', 'Fuel_flow_rate/hour(gal/hr)',
  'Fuel_flow_rate/minute(gal/min)',
  'Fuel_Remaining_(Calculated_from_vehicle_profile)(%)',
  'Fuel_Trim_Bank_1_Long_Term(%)', 'Fuel_trim_bank_1_sensor_1(%)',
  'Fuel_trim_bank_1_sensor_2(%)', 'Fuel_Trim_Bank_1_Short_Term(%)',
  'GPS_Accuracy(m)', 'GPS_Altitude(m)', 'GPS_Bearing(°)',
  'GPS_Latitude(°)', 'GPS_Longitude(°)', 'GPS_Satellites',
  'GPS_vs_OBD_Speed_difference(km/h)', 'Horsepower_(At_the_wheels)(hp)',
  'Intake_Air_Temperature(°C)', 'Intake_Manifold_Pressure(psi)',
  'Kilometers_Per_Litre(Instant)(kpl)',
  'Kilometers_Per_Litre(Long_Term_Average)(kpl)',
  'Litres_Per_100_Kilometer(Long_Term_Average)(l/100km)',
  'Miles_Per_Gallon(Instant)(mpg)',
  'Miles_Per_Gallon(Long_Term_Average)(mpg)',
  'O2_Volts_Bank_1_sensor_1(V)', 'O2_Volts_Bank_1_sensor_2(V)',
  'Relative_Throttle_Position(%)', 'Run_time_since_engine_start(s)',
  'Speed_(GPS)(km/h)', 'Speed_(OBD)(km/h)',
  'Throttle_Position(Manifold)(%)', 'Timing_Advance(°)', 'Torque(Nm)',
  'Trip_average_KPL(kpl)', 'Trip_average_Litres/100_KM(l/100km)',
  'Trip_average_MPG(mpg)', 'Trip_Distance(km)',
  'Trip_Time(Since_journey_start)(s)', 'Trip_time(whilst_moving)(s)',
  'Trip_time(whilst_stationary)(s)', 'Turbo_Boost_&_Vacuum_Gauge(psi)',
  'Turbo_Pressure_Control(psi)', 'Voltage_(Control_Module)(V)',
  'Voltage_(OBD_Adapter)(V)', 'Volumetric_Efficiency_(Calculated)(%)',
  'Fuel_mass', 'Vehicle_speed', 'Km_per_liter'
)


#Shikha
Temperature <- c(
  'Engine_Coolant_Temperature(°C)',
  'Intake_Air_Temperature(°C)'
)

#Shikha
Oil <- c(
  'Fuel_cost_(trip)(cost)',
  'Litres_Per_100_Kilometer(Long_Term_Average)(l/100km)',
  'Engine_Oil_Temperature(°C)'
)

#Shikha
Pressure <- c(
  'Intake_Manifold_Pressure(psi)',
  'Turbo_Boost_&_Vacuum_Gauge(psi)',
  'DPF_Pressure(psi)'
)

#Shikha
Environmental <- c(
  'CO₂_in_g/km_(Average)(g/km)',
  'Barometric_pressure_(from_vehicle)(psi)',
  'Ambient_air_temp(°C)'
)

#Shikha
Acceleration_and_Speed <- c(
  'Acceleration_Sensor(Total)(g)',
  'Acceleration_Sensor(X_axis)(g)',
  'Acceleration_Sensor(Y_axis)(g)',
  'Acceleration_Sensor(Z_axis)(g)',
  'GPS_Speed_(Meters/second)',
  'GPS_vs_OBD_Speed_difference(km/h)'
)

#Harsha
Throttle_and_Pedal_Positions <- c(
  'Absolute_Throttle_Position_B(%)',
  'Accelerator_PedalPosition_D(%)',
  'Accelerator_PedalPosition_E(%)',
  'Accelerator_PedalPosition_F(%)',
  'Throttle_Position(Manifold)(%)',
  'Relative_Throttle_Position(%)'
)

#Harsha
Engine_Performance <- c(
  'Torque(Nm)',
  'Horsepower_(At_the_wheels)(hp)',
  'Engine_kW_(At_the_wheels)(kW)',
  'Engine_Load(%)',
  'Engine_Load(Absolute)(%)',
  'Engine_reference_torque(Nm)',
  'Engine_RPM(rpm)',
  'Actual_engine_%_torque(%)'
)

#Harsha
Time_Location_Provided <- c(
  'GPS_Time',
  'Device_Time',
  'GPS_Bearing(°)',
  'GPS_Latitude(°)',
  'GPS_Longitude(°)',
  'GPS_Satellites',
  'Altitude',
  'Bearing',
  '0-100kph_Time(s)',
  'Trip_Time(Since_journey_start)(s)',
  'Trip_time(whilst_moving)(s)',
  'Trip_time(whilst_stationary)(s)',
  'Horizontal_Dilution_of_Precision',
  'Average_trip_speed(whilst_moving_only)(km/h)',
  'Average_trip_speed(whilst_stopped_or_moving)(km/h)',
  'Speed_(GPS)(km/h)',
  'Speed_(OBD)(km/h)'
)

#Harsha
Electric_Voltage_Provided <- c(
  'Voltage_(Control_Module)(V)',
  'Voltage_(OBD_Adapter)(V)'
)


#Trimmable
trimmable_parameters <- c('Fuel_Trim_Bank_1_Long_Term(%)',
  'Fuel_trim_bank_1_sensor_1(%)',
  'Fuel_trim_bank_1_sensor_2(%)',
  'Fuel_Trim_Bank_1_Short_Term(%)',
  'Volumetric_Efficiency_(Calculated)(%)_Bearing',
  '_G(x)',
  '_G(y)',
  '_G(z)',
  '_G(calibrated)',
  'Absolute_Throttle_Position_B(%)',
  'Relative_Throttle_Position(%)',
  'Accelerator_Pedal_Position_D(%)',
  'Accelerator_PedalPosition_E(%)',
  'Acceleration_Sensor(Total)(g)',
  'Acceleration_Sensor(X_axis)(g)',
  'Acceleration_Sensor(Y_axis)(g)',
  'Acceleration_Sensor(Z_axis)(g)'
  )

#non-trimmable
non_trimmable_parameters <- c('GPS_Time',
                              'Device_Time',
                              'Longitude',
                              'Latitude',
                              'GPS_Speed_(Meters/second)',
                              'Altitude',
                              '0-100kph_Time(s)',
                              'Average_trip_speed(whilst_moving_only)(km/h)',
                              'Average_trip_speed(whilst_stopped_or_moving)(km/h)',
                              'Barometric_pressure_(from_vehicle)(psi)',
                              'CO₂_in_g/km_(Average)(g/km)',
                              'Engine_Coolant_Temperature(°C)',
                              'Engine_kW_(At_the_wheels)(kW)',
                              'Engine_Load(%)',
                              'Engine_Load(Absolute)(%)',
                              'Engine_Oil_Temperature(°C)',
                              'Engine_reference_torque(Nm)',
                              'Engine_RPM(rpm)',
                              'GPS_Accuracy(m)',
                              'GPS_Altitude(m)',
                              'GPS_Bearing(°)',
                              'GPS_Latitude(°)',
                              'GPS_Longitude(°)',
                              'GPS_Satellites',
                              'GPS_vs_OBD_Speed_difference(km/h)',
                              'Horsepower_(At_the_wheels)(hp)',
                              'Intake_Air_Temperature(°C)',
                              'Intake_Manifold_Pressure(psi)',
                              'O2_Volts_Bank_1_sensor_1(V)',
                              'O2_Volts_Bank_1_sensor_2(V)',
                              'Speed_(GPS)(km/h)',
                              'Throttle_Position(Manifold)(%)',
                              'Torque(Nm)',
                              'Turbo_Boost_&_Vacuum_Gauge(psi)',
                              'Turbo_Pressure_Control(psi)',
                              'Voltage_(Control_Module)(V)',
                              'Voltage_(OBD_Adapter)(V)'
                              )

# Trimmable Parameters
trimmable_parameters <- c(
  "CO₂ in g/km (Average)",
  "Trip Distance (km)",
  "Run Time Since Engine Start (s)",
  "Trip Time (Since Journey Start) (s",
  "Trip Time (Whilst Moving) (s)",
  "Trip Time (Whilst Stationary) (s)",
  "Engine Coolant Temperature (°C)",
  "Trip Average KPL (kpl)",
  "O2 Volts Bank 1 Sensor 1 (V)",
  "O2 Volts Bank 1 Sensor 2 (V)",
  "Fuel Flow Rate/Hour (gal/hr)"
)

# The parameters which are following the description:

following_parameters <- c("CO..in.g.km..Average..g.km.", "Trip.Distance.km",
                 "Run.time.since.engine.start.s.", "Engine.Coolant.Temperature..C.",
                 "Litres.Per.100.Kilometer.Long.Term.Average..l.100km.", "Trip.Time.Since.journey.start..s.","Trip.time.whilst.stationary..s.",
                 "Trip.time.whilst.moving..s.", "Trip.average.KPL.kpl.",
                 "O2.Volts.Bank.1.sensor.1.V.", "O2.Volts.Bank.1.sensor.2.V.", "Fuel.flow.rate.hour.gal.hr.","Trip.time.whilst.stationary..s.","Engine.kW..At.the.wheels..kW.", "Horsepower..At.the.wheels..hp.","Trip.average.Litres.100.KM.l.100km.","Absolute.Throttle.Position.B...","Relative.Throttle.Position...","Accelerator.PedalPosition.D...","Accelerator.PedalPosition.E...","Throttle.Position.Manifold....","Kilometers.Per.Litre.Instant..kpl.","Miles.Per.Gallon.Instant..mpg.","G.x.","Miles.Per.Gallon.Long.Term.Average..mpg.","Engine.RPM.rpm.","Intake.Air.Temperature..C.")
                 
      



    