---
title: "Trip_Based_Performance"
output: html_document
date: "2023-10-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
data_pre = read.csv('/Users/sanjayramrajasrinsanjayivasan/Documents/GitHub/Intro_to_data_science_project/dataset.csv')
data_pre$Cluster = as.character(data_pre$Cluster)
str(data_pre)
```

```{r}
library(ggplot2)
ggplot(data_pre,aes(x=Fuel_mass,y=Cluster)) + geom_boxplot(fill = "#66c2a5", color = "#7570b3") + 
  labs(title = "Fuel Mass across the Clusters",
       x = "Fuel Mass",
       y = "Cluster") +  
  theme_minimal() 
cache=FALSE
```


```{r}
ggplot(data_pre,aes(x=Trip.average.KPL.kpl.,y=Cluster)) + geom_boxplot(fill = "#66c2a5", color = "#7570b3") + 
  labs(title = "Fuel Mass across the Clusters",
       x = "Trip.average.KPL.kpl. ",
       y = "Cluster") +  
  theme_minimal() 
cache=FALSE
```
```{r}
data_pre_o <- data_pre[data_pre$Cluster == "3" | data_pre$Cluster == "5",]
ggplot(data_pre_o, aes(x =Trip.average.KPL.kpl., fill = Cluster)) +
  geom_histogram(position = "identity", alpha = 0.4) + scale_x_continuous(limits = c(11, 13))
```

```{r}
ci_list <- list()
confidence_level <- 0.95

for (cluster_id in unique(data_pre$Cluster)) {
  subset_data <- data_pre[data_pre$Cluster == cluster_id, ]
  
  t_test_result <- t.test(subset_data$Trip.average.KPL.kpl., conf.level = confidence_level)
  ci <- t_test_result$conf.int

  ci_list[[as.character(cluster_id)]] <- ci
}
print(ci_list)
```
```{r}
library(ggplot2)

# Set the plot width and height
options(repr.plot.width=10, repr.plot.height=6)

ggplot(data_pre,aes(x=Trip.average.Litres.100.KM.l.100km.,y=Cluster)) + geom_boxplot(fill = "#66c2a5", color = "#7570b3") + 
  labs(title = "Fuel Mass across the Clusters",
       x = "Trip.average.Litres.100.KM.l.100km.",
       y = "Cluster") +  
  theme_minimal() 
cache=FALSE
```

```{r}
data_pre_t <- data_pre[data_pre$Cluster == "2" | data_pre$Cluster == "5",]
ggplot(data_pre_t, aes(x =Trip.average.Litres.100.KM.l.100km., fill = Cluster)) +
  geom_histogram(position = "identity", alpha = 0.4) + scale_x_continuous(limits = c(5, 15))
```
```{r}
ci_list <- list()
confidence_level <- 0.95

for (cluster_id in unique(data_pre$Cluster)) {
  subset_data <- data_pre[data_pre$Cluster == cluster_id, ]
  
  t_test_result <- t.test(subset_data$Trip.average.Litres.100.KM.l.100km., conf.level = confidence_level)
  ci <- t_test_result$conf.int

  ci_list[[as.character(cluster_id)]] <- ci
}
print(ci_list)
```


